language: php
sudo: false
dist: trusty

matrix:
  fast_finish: true
  include:
    - php: 7.2
      env: CS_FIX=true PHPSTAN=true SEND_COVERAGE=true
    - php: 7.3
    - php: 7.1
    - php: nightly
  allow_failures:
    - php: nightly

env:
  global:
    - SEND_COVERAGE=false
    - CS_FIX=false
    - PHPSTAN=false

before_script:
  - mkdir -p test/logs
  - mkdir -p tests/tmp/cache 
  - mkdir -p build/logs
  - mysql -e "DROP DATABASE IF EXISTS phpunit_soluble_schema_db;" -u root
  - mysql -e "CREATE DATABASE phpunit_soluble_schema_db;" -u root
  - zcat test/data/mysql/schema.sql.gz | mysql -u root phpunit_soluble_schema_db
  - zcat test/data/mysql/data.sql.gz | mysql -u root phpunit_soluble_schema_db
  - mysql -e "SHOW DATABASES;" -u root
  - mysql -e "CONNECT phpunit_soluble_schema_db; SHOW TABLES;" -u root
  - composer install --no-interaction --ignore-platform-reqs

script:
  - ./vendor/bin/phpunit -v --coverage-clover=coverage.xml
  - if [[ $CS_FIX == true ]]; then ./vendor/bin/php-cs-fixer --diff --dry-run -v fix; fi;
  - if [[ $PHPSTAN == true ]]; then composer phpstan; fi;


after_script:
  - if [[ $SEND_COVERAGE == true ]]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [[ $SEND_COVERAGE == true ]]; then php ocular.phar code-coverage:upload --format=php-clover coverage.xml; fi
  - if [[ $SEND_COVERAGE == true ]]; then bash <(curl -s https://codecov.io/bash); fi
