language: php
dist: trusty

matrix:
  fast_finish: true
  include:
    - php: 7.2
      env: MYSQL_VERSION=5.6
    - php: 7.1
      env: SEND_COVERAGE=true MYSQL_VERSION=5.6
    - php: 7.1
      env: MARIADB_VERSION=10.2
      addons:
        mariadb: '10.2'
    - php: 7.1
      env: MARIADB_VERSION=10.1
      addons:
        mariadb: '10.1'
    - php: 7.1
      env: MARIADB_VERSION=10.0
      addons:
        mariadb: '10.0'
    - php: 7.1
      env: MYSQL_VERSION=5.7
      addons:
        mysql: '5.7'
    - php: 7.0
      env: MYSQL_VERSION=5.6
    - php: 5.6
      env: MYSQL_VERSION=5.6
    - php: 5.5
      env: MYSQL_VERSION=5.6
    - php: 5.4
      env: MYSQL_VERSION=5.6
    - php: nightly
      env: MYSQL_VERSION=5.6
  allow_failures:
    - php: nightly
          
env:
  global:
    - SEND_COVERAGE=false

before_script:
  - mkdir -p test/logs
  - mkdir -p tests/tmp/cache 
  - mkdir -p build/logs
  - mysql -e "DROP DATABASE IF EXISTS phpunit_soluble_schema_db;" -u root
  - mysql -e "CREATE DATABASE phpunit_soluble_schema_db;" -u root
  - zcat test/data/mysql/schema.sql.gz | mysql -u root phpunit_soluble_schema_db
  - zcat test/data/mysql/data.sql.gz | mysql -u root phpunit_soluble_schema_db
  - mysql -e "SHOW DATABASES;" -u root
  - mysql -e "CONNECT phpunit_soluble_schema_db; SHOW TABLES;" -u root
  - if [[ "$MYSQL_VERSION" == "5.7" ||
          "$MYSQL_VERSION" == "5.6" ||
          "$MARIADB_VERSION" == "10.2" ||
          "$MARIADB_VERSION" == "10.1" ||
          "$MARIADB_VERSION" == "10.0" ]]; then
       mysql -u travis -e "select version()";
    fi;
  - travis_retry composer self-update
  - travis_retry composer install

script:
  - ./vendor/bin/phpunit -v --coverage-clover=coverage.xml
  - ./vendor/bin/php-cs-fixer --diff --dry-run -v fix

after_script:
  - if [[ $SEND_COVERAGE == true ]]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [[ $SEND_COVERAGE == true ]]; then php ocular.phar code-coverage:upload --format=php-clover coverage.xml; fi
  - if [[ $SEND_COVERAGE == true ]]; then bash <(curl -s https://codecov.io/bash); fi
